version: '3.9'
services:
  backend:
    container_name: fazo4-backend
    build: ./back-end
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /back-end
    environment:
      - NODE_ENV=development
      - API_PORT=3001
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=senhaDoDB
      - MYSQL_DB_NAME=delivery-app
      - EVAL_ALWAYS_RESTORE_DEV_DB=true
  db:
    image: mysql:8.0.21
    container_name: fazo4-db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senhaDoDB
    restart: 'always'